[1/4] handleTechSeeked_ is not a function
1/4 compatibility fix VideoJs 7+

Error after switching quality
> VIDEOJS: ERROR: TypeError: player.play(...).handleTechSeeked_ is not a function at Player. (videojs-resolution-switcher.js:184)
This is probably due to the exclusion of the flash from the kernel.
https://blog.videojs.com/video-js-removes-flash-from-core-player/

https://github.com/kmoskwiak/videojs-resolution-switcher/issues/129#issue-428996077